version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          set -x
          apk --no-cache add sudo curl bash util-linux socat
          apk add --no-cache -t .deps ca-certificates
          export GLIBC_VERSION='2.23-r3'
          curl -Lo /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
          curl -Lo glibc.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$GLIBC_VERSION/glibc-$GLIBC_VERSION.apk
          curl -Lo glibc-bin.apk https://github.com/sgerrand/alpine-pkg-glibc/releases/download/$GLIBC_VERSION/glibc-bin-$GLIBC_VERSION.apk
          apk update
          apk add glibc.apk glibc-bin.apk
          rm -rf /var/cache/apk/*
          rm glibc.apk glibc-bin.apk
          apk del .deps
          apk add --no-cache -t .deps ca-certificates
          DOCKER_COMPOSE_URL=https://github.com$(curl -L https://github.com/docker/compose/releases/latest | grep -Eo 'href="[^"]+docker-compose-Linux-x86_64' | sed 's/^href="//' | head -1)
          curl -Lo /usr/local/bin/docker-compose $DOCKER_COMPOSE_URL
          chmod a+rx /usr/local/bin/docker-compose
          docker-compose version
          apk del .deps
