version: 2
jobs:
  build:
    docker:
      - image: docksal/cli:1.3-php7
        name: cli
        environment:
          DOCROOT=web
      - image: docksal/web:2.1-apache2.4
        name: web
        environment:
          APACHE_DOCUMENTROOT=/var/www/web
      - image: docksal/db:1.1-mysql-5.6
        name: db
        environment:
          MYSQL_ROOT_PASSWORD=root
          MYSQL_USER=user
          MYSQL_PASSWORD=user
          MYSQL_DATABASE=default
    steps:
      - checkout
      - setup_remote_docker
