version: 2
jobs:
  build:
    working_directory: /var/www/
    docker:
      - image: seandietrich/php:latest
        environment:
          - APACHE_DOCUMENTROOT: /var/www/docroot
      - image: mariadb:latest
        name: db
        environment:
          - MYSQL_ROOT_PASSWORD: root
          - MYSQL_DATABASE: drupal
          - MYSQL_USER: user
          - MYSQL_ROOT_PASSWORD: user
      - image: selenium/standalone-chrome
        name: browser
    steps:
      - run: rm -rf /var/www/*
      - run: echo " StrictHostKeyChecking no" >> /etc/ssh/ssh_config
      - checkout
