version: 2
jobs:
  build:
    working_directory: /var/www/
    docker:
      - image: docksal/cli:php7
        name: cli
        environment:
          - DOCROOT: docroot
        links:
          - web
          - db
          - browser
      - image: docksal/web:2.1-apache2.4
        name: web
        environment:
          - APACHE_DOCUMENTROOT: /var/www/docroot
      - image: docksal/db:1.1-mysql-5.6
        name: db
        ports: 3306
        environment:
          - MYSQL_ROOT_PASSWORD: root
          - MYSQL_DATABASE: drupal
          - MYSQL_USER: user
          - MYSQL_ROOT_PASSWORD: user
      - image: selenium/standalone-chrome
        name: browser
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - checkout
