version: 2
jobs:
  build:
    working_directory: /var/www/
    docker:
      - image: circleci/php:7-apache-node-browsers
        environment:
          - DRUSH_VERSION: 8.1.13
          - DRUPAL_CONSOLE_VERSION: 1.0.2
      - image: circleci/mysql:5.6-ram
      - image: selenium/standalone-chrome
        name: browser
    steps:
      - run: rm -rf /var/www/*
      - checkout
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Installing Drupal Console
          command: curl -sSL "https://github.com/hechoendrupal/drupal-console-launcher/releases/download/${DRUPAL_CONSOLE_VERSION}/drupal.phar" -o /usr/local/bin/drupal
      - run:
          name: Drupal Console Version
          command: drupal --version
      - run:
          name: Install Drush
          command: curl -sSL "https://github.com/drush-ops/drush/releases/download/${DRUSH_VERSION}/drush.phar" -o /usr/local/bin/drush
      - run:
          name: Drush Version
          command: drush --version
      - run:
          name: Creating Files Directory
          command: mkdir docroot/sites/default/settings.php
      - run:
          name: Fixing Files Directory Permission
          command: chmod 755 docroot/sites/default/settings.php
      - run:
          name: Copying Standard Settings file
          command: cp .circleci/settings.php docroot/sites/default/settings.php
      - run:
          name: Drush Site Install
          command: drush site-install -y --site-name='My Drupal 8 Site'
          working_directory: /var/www/docroot/
